# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter bloomxq c1q c2q f2q gts7l gts7lwifi gts7xl gts7xlwifi r8q x1q y2q z3q,$(TARGET_DEVICE)),)

endif
